### ISSUE TITLE
AttributeError: 'ElementHandle' object has no attribute 'evaluate'

### ISSUE THREAD

**Issue by kikikikikinanana** [mcolella14/python_ghost_cursor#4] opened 2021-06-24 16:36 UTC
from pyppeteer_ghost_cursor import createCursor
import pyppeteer
import asyncio
url = 'https://www.naver.com'
async def main(url):
  selector = "#account > a"
  browser = await pyppeteer.launch(headless=False)
  page = await browser.newPage()
  cursor = createCursor(page)
  await page.goto(url)
  await page.waitForSelector(selector)
  await cursor.click(selector)

asyncio.run(main(url))

error:
Traceback (most recent call last):
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\site-packages\pyppeteer_ghost_cursor-0.1-py3.8.egg\pyppeteer_ghost_cursor\spoof.py", line 244, in move
    await self.page._client.send(
pyppeteer.errors.NetworkError: Protocol error (DOM.scrollIntoViewIfNeeded): 'DOM.scrollIntoViewIfNeeded' wasn't found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/TETETE/PycharmProjects/untitled/complete_exp/Drawbot 2.0.py", line 14, in <module>
    asyncio.run(main(url))
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/TETETE/PycharmProjects/untitled/complete_exp/Drawbot 2.0.py", line 12, in main
    await cursor.click(selector)
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\site-packages\pyppeteer_ghost_cursor-0.1-py3.8.egg\pyppeteer_ghost_cursor\spoof.py", line 201, in click
    await self.move(selector, paddingPercentage, waitForSelector)
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\site-packages\pyppeteer_ghost_cursor-0.1-py3.8.egg\pyppeteer_ghost_cursor\spoof.py", line 249, in move
    await elem.evaluate(
AttributeError: 'ElementHandle' object has no attribute 'evaluate'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\site-packages\pyppeteer\launcher.py", line 152, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\asyncio\base_events.py", line 591, in run_until_complete
    self._check_closed()
  File "C:\Users\TETETE\anaconda3\envs\bot\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by mcolella14** [comment] 2021-06-25 13:22
The root cause is the same as the one for #3, just need support for the `dev` branch.

**Comment by kikikikikinanana** [comment] 2021-06-27 15:06
You will fix only this issue!!!

**Comment by mcolella14** [comment] 2021-06-27 15:43
What is your pyppeteer version?

**Comment by kikikikikinanana** [comment] 2021-06-27 16:33
i installed lastest version
pip install -U git+https://github.com/pyppeteer/pyppeteer@dev
use this command

**Comment by mcolella14** [comment] 2021-06-28 14:10
Sorry about this, I misread the source code for the pyppeteer@dev branch. This issue should now be fixed with #7 (I tested your code verbatim and it works for me).

**Comment by kikikikikinanana** [comment] 2021-06-29 15:20
It working! Thanks
BTW, how to see mouse pointer in pyppeteer when ghost cursor working?

**Comment by mcolella14** [comment] 2021-06-29 15:34
Awesome, no problem! And for that you can use the `installMouseHelper` function. In your example it would be like this: 
```python
from pyppeteer_ghost_cursor import createCursor, installMouseHelper
import pyppeteer
import asyncio
url = 'https://www.naver.com'
async def main(url):
    selector = "#account > a"
    browser = await pyppeteer.launch(headless=False)
    page = await browser.newPage()
    await installMouseHelper(page)
    cursor = createCursor(page)
    await page.goto(url)
    await page.waitForSelector(selector)
    await cursor.click(selector)

asyncio.run(main(url))
```

**Closed as completed** 2021-06-30 09:54 UTC
